### ISSUE TITLE
今日额度已用完，

### ISSUE THREAD

**Issue by xiaojiewang28** [itewqq/MathF#10]
都没用过，怎么就显示免费额度已用完

**Comment by itewqq** [comment]
为了防止有人换ip滥用，额度是按天配置的，不是按每个用户配置的
可能上午的时候有人用太多用完了

**Comment by houdezaiwu2019** [comment]
请问几时算一天的开始，为什么我十二点以后就用了半个消失就显示没有的？

**Comment by houdezaiwu2019** [comment]
**请问几时算一天的开始，为什么我十二点以后就用了半个小时就显示没有的？**

**Comment by itewqq** [comment]
> **请问几时算一天的开始，为什么我十二点以后就用了半个小时就显示没有的？**

应该是12点算开始，那可能有人在半个小时内把今日的额度用完了 😭

**Comment by houdezaiwu2019** [comment]
前几天，我上午显示没有了，后来晚上有了，感觉这个计时好像不是北京时间。

**Comment by itewqq** [comment]
咦？那我再看看

**Comment by houdezaiwu2019** [comment]
今天好像又正常了，我也搞不懂，请问每天最多1000次吗？

**Comment by houdezaiwu2019** [comment]
> > **请问几时算一天的开始，为什么我十二点以后就用了半个小时就显示没有的？**
> 
> 应该是12点算开始，那可能有人在半个小时内把今日的额度用完了 😭

请问每天多少次？
