### ISSUE TITLE
公式加载不出来~

### ISSUE THREAD

**Issue by kim000917** [itewqq/MathF#2]
重启电脑，刷新依然是这样的界面
![image](https://user-images.githubusercontent.com/76483387/102895790-4fd8da80-44a0-11eb-9266-82b757c24ac0.png)

**Comment by itewqq** [comment]
@Alyoshkakim 你的图像是多行公式吗？目前已知多行公式的识别是有bug的，需要手动一行一行识别。另外公式夹杂汉字的情况也有一定几率会出bug。
