### ISSUE TITLE
有考虑过使用vercel代替heroku吗？

### ISSUE THREAD

**Issue by zhongfly** [itewqq/MathF#3]
heroku速度确实不太行，https://vercel.com/ 到国内的速度还算快。
如果不是docker，vercel支持的和heroku差不多

**Comment by itewqq** [comment]
感谢建议。考完期末考试之后我会更新一下服务，届时会考虑一下使用vercel的情况。

**Comment by itewqq** [comment]
已经从heroku移植到国内自用主机。
