### ISSUE TITLE
总是反馈错误

### ISSUE THREAD

**Issue by newyq** [itewqq/MathF#5]
![图片](https://user-images.githubusercontent.com/66189362/108165970-72007900-712e-11eb-97a1-aa496731b63b.png)
![图片](https://user-images.githubusercontent.com/66189362/108165987-79278700-712e-11eb-9d49-410baddb4f32.png)
![图片](https://user-images.githubusercontent.com/66189362/108166034-8b092a00-712e-11eb-84c3-890ef76b400b.png)
这个是今天返回的错误，不知道是什么情况

**Comment by itewqq** [comment]
@haibokuang 可以刷新几次页面试试。

**Comment by newyq** [comment]
> @haibokuang 可以刷新几次页面试试。
好的，谢谢
